services:
  mariadb:
    image: mariadb:1
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
  nginx:
    image: nginx:1
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
      - ../secrets/inception.crt:/run/secrets/inception.crt:ro
      - ../secrets/inception.key:/run/secrets/inception.key:ro
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: always
  wordpress:
    image: wordpress:1
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"
  redis:
    image: redis:1
    container_name: redis
    depends_on:
      - wordpress
    volumes:
      - redis:/data
    networks:
      - inception
    build: requirements/bonus/redis
    expose:
      - "6379"
    restart: always
  ftp:
    image: ftp:1
    container_name: ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    build: requirements/bonus/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: unless-stopped
  adminer:
    image: adminer:1
    container_name: adminer
    build: requirements/bonus/adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
  portainer:
    image: portainer:1
    container_name: portainer
    build: requirements/bonus/portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    ports:
      - "9443:9443"
    restart: unless-stopped
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dagimeno/data/wordpress_db
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dagimeno/data/wordpress_files
  redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dagimeno/data/redis_db
  portainer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dagimeno/data/portainer
networks:
  inception:
    driver: bridge
